### ISSUE TITLE
Lükenhafte Excel-Tabelle

### ISSUE THREAD

**Issue by ghost** [ski7777/ft-industry#1]
Hallo ski7777,
ich hab dich jetzt schon so oft im Forum gesehen und scha jetzt auch mal hier vorbei. Ich weiß nicht, ob dass so gewollt ist, aber in der Dokumentation fehlt einmal M3.

Grüße, Dein
raspberrypi

**Comment by ski7777** [comment]
Habs gefixt. War wohl aus versehen passiert.
@raspberrypi-tonline Wer bist du? Ich kenne dich nicht?

Raphael

**Comment by ghost** [comment]
Och, dass musst du nicht wissen...Erzähl du von dir, dann erzähl ich von 
mir.
